// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzhobuwsmxbobqkruvhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6aG9idXdzbXhib2Jxa3J1dmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTg2NzcsImV4cCI6MjA2NzU5NDY3N30.oQPEssbpJuZTMuYwNBqU_D3gjpHoEs06C0NEuRWLWps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});